id: A9AADCA06
title: Magnetizing (Wangdü) Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:31:28.909537
  last_modified_at: 2022-03-01 04:31:28.909544
